import type { NextPage } from "next";
import Head from "next/head";
import LandingPage from "../components/LandingPage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SpaceX Rocket Launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPage />
    </>
  );
};

export default Home;
